spring:
  application:
    name: ai-super-agent
  ai:
    chat:
      client:
        enabled: false
    # ????????token????openAi??????qwen
    openai:
      api-key: { your api-key }
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen3.5-plus
      embedding:
        api-key: { your api-key }
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        options:
          model: text-embedding-v4
          dimensions: 1536
    dashscope:
      chat:
        options:
          model: qwen-plus


  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://rm-cn-5y44s1zdo0002w8o.rwlb.rds.aliyuncs.com:5432/ai_agent
    username: my_root
    password: {your password}

server:
  port: 8080
  servlet:
    context-path: /api

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.greg.aisuperagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    #org.springframework.web.client: debug
    #com.alibaba.cloud.ai.dashscope: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG